model: 'LSTM'

lstm_hidden_size: 32

lstm_num_layers: 3

epochs: 30

batch_size: 32

seq_len: 10

window_size: 10

learning_rate: 0.005

weight_decay: 0.0001

early_stop_epochs: 3

patience: 3

lr_scheduler: 'None'

track_lstm_cell_states: True